title: Carolina Compensation and Rewards Association
description: Professional community for compensation and total rewards leaders across North and South Carolina.
theme: jekyll-theme-primer
last_updated: 2026-02-21
exclude:
  - docExport
  - Gemfile
  - Gemfile.lock
